import{a as E,S as L,i as m}from"./assets/vendor-b11e2a50.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&t(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const P="45010101-f091bc02c96679130727c6b77",S="https://pixabay.com/api/",v=15;let d=1,h="";async function y(){try{const o=await E.get(S,{params:{key:P,q:h,image_type:"photo",orientation:"horizontal",safesearch:"true",page:d,per_page:v}}),s=o.data.hits,n=o.data.totalHits;return{images:s,totalHits:n}}catch(o){throw console.error("Error fetching images:",o),o}}function q(){d=1}function I(){d+=1}function $(o){h=o}function O(){return d}function f(o){const s=document.querySelector(".gallery"),n=o.map(t=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${t.largeImageURL}" data-title="${t.tags}">
        <img 
          class="gallery-image" 
          src="${t.webformatURL}" 
          alt="${t.tags}" 
        />
        <div class="gallery-info">
          <p class="info-item"><b>Likes</b>: ${t.likes}</p>
          <p class="info-item"><b>Views</b>: ${t.views}</p>
          <p class="info-item"><b>Comments</b>: ${t.comments}</p>
          <p class="info-item"><b>Downloads</b>: ${t.downloads}</p>
        </div>
      </a>
    </li>
      `).join("");s.insertAdjacentHTML("beforeend",n)}function R(){iziToast.error({title:"Error",message:"Sorry, there are no images. Please try again!"})}function g(){iziToast.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})}const p=15;document.addEventListener("DOMContentLoaded",()=>{const o=document.querySelector("#search-form"),s=document.querySelector("#search-input"),n=document.querySelector(".gallery"),t=document.querySelector(".loader"),e=document.querySelector("#load-more");if(!o||!s||!n||!e){console.error("Form, input, gallery, or load more button element not found");return}const r=new L(".gallery a",{captions:!0,captionsData:"title",captionDelay:250});let a=0;o.addEventListener("submit",async l=>{l.preventDefault();const c=s.value.trim();if(c===""){m.error({title:"Error",message:"Search query can't be empty!"});return}t.style.display="block",e.style.display="none",$(c),q();try{const{images:i,totalHits:u}=await y();a=u,n.innerHTML="",i.length===0?R():(f(i),r.refresh(),e.style.display=a>p?"block":"none")}catch(i){console.error("Error fetching images:",i),m.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{t.style.display="none"}}),e.addEventListener("click",async()=>{t.style.display="block",I();try{const l=document.querySelector(".gallery-item:last-child"),{images:c}=await y(),i=O();if(c.length>0){f(c),r.refresh();const u=document.querySelectorAll(".gallery-item img"),b=u[u.length-1];b.onload=()=>{if(l){const w=l.nextElementSibling.getBoundingClientRect().top+window.scrollY;window.scrollTo({top:w,behavior:"smooth"})}},i*p>=a&&(e.style.display="none",g())}else e.style.display="none",g()}catch(l){console.error("Error fetching images:",l),m.error({title:"Error",message:"Failed to fetch more images. Please try again later."})}finally{t.style.display="none"}})});
//# sourceMappingURL=commonHelpers.js.map
